# Generated by Django 3.2.11 on 2022-01-29 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('bill_no', models.AutoField(primary_key=True, serialize=False, verbose_name='Bill No.')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('mobile', models.BigIntegerField(verbose_name='Contact Number')),
                ('address', models.TextField(verbose_name='Address')),
                ('amount', models.FloatField(verbose_name='Order_amount')),
                ('items', models.PositiveBigIntegerField(verbose_name='Number Of Items')),
                ('order_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveBigIntegerField(default=1, verbose_name='Quantity')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product', verbose_name='Product Id')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User Id')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100, verbose_name='Item Name')),
                ('quantity', models.PositiveBigIntegerField(verbose_name='Quantity')),
                ('mrp', models.FloatField(verbose_name='MRP/Quantity')),
                ('total', models.FloatField(verbose_name='Total')),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('bill_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.order', verbose_name='Order Id')),
            ],
        ),
    ]
