# Generated by Django 3.2.11 on 2022-01-29 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20220130_0042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='items',
            new_name='no_of_items',
        ),
    ]
