# Generated by Django 3.2.11 on 2022-01-29 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_rename_items_order_no_of_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='bill_no',
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='bill_no_id',
            field=models.ForeignKey(default=24, on_delete=django.db.models.deletion.CASCADE, to='cart.order', verbose_name='Bill No'),
            preserve_default=False,
        ),
    ]
