# Generated by Django 3.2.11 on 2022-01-29 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_auto_20220130_0216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetail',
            old_name='bill_no_id',
            new_name='bill_no',
        ),
    ]
